apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cake-manger
  name: cake-manger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-manger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cake-manger
    spec:
      containers:
      - image: waytowalkin/cake-manger:0.0.3.RELEASE
        imagePullPolicy: IfNotPresent
        name: cake-manger
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cake-manger
  name: cake-manger
  namespace: default
spec:
  ports:
  - nodePort: 30950
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cake-manger
  sessionAffinity: None
  type: LoadBalancer